### PR TITLE
[docs] Initial structure for sphinx-js docs

### PR DESCRIPTION
**Pull request by danielfranca**
#### Changes
* Initial documentation using sphinx

#### Verification
* To generate the documentation:
`cd docs`
Run the build command with one of the supported formats, i.e:
`make html`

* Open the documentation index: `docs/build/html/index.html`

### CODE REVIEW

**Comment by florianlenz** [comment]
I can't run `make` in the root folder. I think it make sense to put the `Makefile` in the root of the project and put the doc files in the `docs` folder.

**Comment by danielfranca** [comment]
I have tried for some time to make it work with Sphinx
But I got a few issues.
The last one was related to flow, it doesn't recognize flow syntax natively, and I had to add a layer of babel, and in the end it didn't work and it was becoming overcomplicated.

And then I found this tool: https://github.com/documentationjs/documentation
That already extract jsdoc from modern Javascript, including flow, with no additional steps.

I have added a npm command
`npm run docs`

That should generate the documentation on the docs folder

This is how it looks like
screenshot-2018-3-29 pangea 0 0 1 documentation

Now I need to figure out if and how I can integrate it on readthedocs

**Comment by florianlenz** [comment]
@danielfranca I will add you to bitrise. Please send me your email via DM. You can just strip the flow types. So you would end up having a `raw_js` folder with the native es6/es7. I also tried to use tools like documentation.js but the problem is that we can't add additional documenation that is not related to the code. E.g. you might want to describe how profiles work and then add the methods as a reference. That's the reason why I would like to use sphinx js + sphinx

**Comment by danielfranca** [comment]
@florianlenz As far as I understand, you can add it in the documentation.js configuration, adding narratives for the functions: https://github.com/documentationjs/documentation/blob/master/docs/CONFIG.md

**Comment by florianlenz** [comment]
@danielfranca I will check it out. Another option would maybe to write a short sphinx extension that parses JSON generated by documentation.js and then put it in the sphinx documentation. We could keep that simple. We basically just need to reference function's and classes.

**Comment by danielfranca** [comment]
@florianlenz 
 I have added 2 commands
`npm run docs:html` for html output
`npm run docs:md` for markdown output

**Comment by florianlenz** [comment]
@danielfranca This type of documentation is not the one I am looking for. Primary focus is on architecture documentation / trouble shooting guides etc. BUT we still want to include JS code documentation like type's etc. Please stick to the requirements form [this issue](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/issues/318). IF we can't get sphinx-js working you can parse JSON generated by documentation.js like this: http://documentation.js.org/html-example/index.json and build a sphinx extension. It shouldn't be too hard (you know python as far as I remember, right?)

**Comment by danielfranca** [comment]
@florianlenz  Please, update the issue with the detailed specification of what you want to document.

**Comment by florianlenz** [comment]
@danielfranca I updated it.

**Comment by danielfranca** [comment]
Thanks, I'll take a look Today

**Pull request closed without merging**
