### PR TITLE
Fix/56 realm path

### PR DESCRIPTION
**Pull request by florianlenz**
closes: #56 

#### Changes
* updated the panthalassa db

#### Verification
* see the CI passing

### CODE REVIEW

**Comment by florianlenz** [comment]
@seland Can you check if it compiles on android?

**Comment by seland** [comment]
@florianlenz To check if container works I add that line:
`import container from '../../services/container';` 
into src/screens/wallet/index.js. After building the I got it crashed totally (not the red screen, but native app crash). Android Studio logs says:
```
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6364 (mqt_native_modu)

        [ 01-12 19:11:39.501  1262: 1262 W/         ]
        debuggerd: handling request: pid=5943 uid=10091 gid=10091 tid=6364
```

What I can find on this, is that happens when app is not responding, like doing some infinite loop on main thread, then system kills the app. Do you have any idea, what can causing it?

**Comment by florianlenz** [comment]
Did you try to run it on IOS? If not I am on the way. I have no Idea what could cause it.

**Comment by florianlenz** [comment]
@seland 

The CI is failing with the following error: 
```
"Install Android SDK Platform 27" failed.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-crop-picker'.
      > Failed to install the following SDK components:
        [Android SDK Platform 27]
        Please install the missing components using the SDK manager in Android Studio.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```

Are you sure the error depend on my changes?

**Comment by seland** [comment]
@florianlenz CI failing looks like Android SDK Platform 27 is not installed on CI server, so the build process can't be completed. 
Error that I had happened after build is finished and the app load js bundle, so these are two unrelated errors).

**Comment by florianlenz** [comment]
Strange. The previous two build's passed ...

**Comment by seland** [comment]
@florianlenz Fix the crash by replacing start function in /src/services/panthalassa/ethDaemon.js with
`start: () => null,`
Seems that ethDaemon hands the app.

**Comment by florianlenz** [comment]
Did you commit that?

**Comment by florianlenz** [comment]
@seland if you fix the database path in the current dev branch, is the daemon then starting / is your app compiling? If not it's a problem with this branch. I remember that I updated the dep's so that might cause the problem.

**Comment by seland** [comment]
@florianlenz Dev branch crashed the same way. I've posted an [issue](https://github.com/Bit-Nation/react-native-eth-daemon/issues/11) on eth-daemon repo. Actually, your fix is working, since realm opens correctly now, so I suggest we drop ethDaemon start call for now, place todo there and merge that pull request. What do you think?

**Comment by florianlenz** [comment]
@seland can you try to run it on an real android device? @albertoestarrona mentioned in private chat that there are some problem's with the simulator devices. That way we are sure that it's not my branch that is causing the problems.

**Comment by seland** [comment]
@florianlenz I don't have Android device at the moment. I'll try to get it from someone to test tomorrow

**Comment by seland** [comment]
@florianlenz This PR resolves already closed issue, so we can close it as well.

**Pull request closed without merging**
